---
- hosts: armservers
  remote_user: root
  tasks:
    - name: Update repositories
      apt:
        update_cache: yes
    - name: Install a few utility tools.
      apt: name={{item}}
      with_items:
           - tar
           - wget
           - git
           - htop
    - name: Install the latest OpenJDK.
      apt:
        name: openjdk-8-jdk
    - name: Create simlink to Java for Jenkins.
      file:
        path: /home/jenkins/tools/java/jdk1.8.0_131/bin/
        state: directory
    - name: Create simlink to Java for Jenkins.
      file:
        src: /usr/bin/java
        dest: /home/jenkins/tools/java/jdk1.8.0_131/bin/java
        state: link
    - name: Install autotools (Only necessary if building from git repository).
      apt: name={{item}}
      with_items:
           - autoconf
           - libtool
    - name: Install other Mesos dependencies.
      apt: name={{item}}
      with_items:
          - build-essential
          - python-dev
          - python-six
          - python-virtualenv
          - libcurl4-nss-dev
          - libsasl2-dev
          - libsasl2-modules
          - maven
          - libapr1-dev
          - libsvn-dev
          - zlib1g-dev
    - name: Remove useless packages from the cache
      apt:
        autoclean: yes
    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes

    # https://reference.apache.org/committer/node-hosting
    - name: Create a jenkins group
      group:
        name: jenkins
    - name: Create a jenkins user
      user:
        name: jenkins
        group: jenkins
    - name: Add in the jenkins ssh public key into the users ~/.ssh/authorized keys
      authorized_key:
        user: jenkins
        key: https://raw.githubusercontent.com/apache/infrastructure-puppet/deployment/modules/build_slaves/files/jenkins.pub

    # https://gist.github.com/phillipuniverse/7721288
    - name: Install NTP
      apt:
        name: ntp
      tags: ntp
    - name: Copy over the NTP configuration
      template: src=etc/ntp.conf dest=/etc/ntp.conf
      notify:
        - restart ntp
        - force ntp update
      tags: ntp
    - name: Make sure NTP is started up
      service: name=ntp state=started enabled=yes
      tags: ntp

    - name: Create a developers group
      group:
        name: dev

  handlers:
    - name: restart ntp
      service:
        name: ntp
        state: restarted
    - name: force ntp update
      shell: "service ntp stop && service ntp start"
